### ISSUE TITLE
超时断开逻辑是不是有问题？

### ISSUE THREAD

**Issue by baoqp** [YukunJ/Turtle#38]
server在poll到连接新的事件时，貌似没有更新连接的超时时间。

**Comment by YukunJ** [comment]
Thanks for pointing this out. Indeed I think I forgot to **refresh** the timer for a client connection when new messages arrive.

I have cooked up a patch here for your reference. [[commits]](https://github.com/YukunJ/Turtle/commit/6728bd41df4bed6d5f52ffb8dcb1d349e12a5aef)

I hooked the refresh functionality together with customer-provided handler function, so that when a new event arrives for a client connection, the first thing it does is to refresh its timer.

And thanks your observation, I even find a subtle lifecycle race problem as in #39.
